import json
import datetime as dt
import textwrap

from .. import __version__


def table_name_to_ref(name):
    return name.replace(":", "_")


def json_data_to_json(json_data, buffer_or_path=None, indent=2):
    is_path = False
    if isinstance(buffer_or_path, str):
        is_path = True
        buffer_or_path = open(buffer_or_path, "w")

    try:
        if buffer_or_path is None:
            return json.dumps(json_data, indent=indent)
        return json.dump(json_data, buffer_or_path, indent=indent)
    finally:
        if is_path:
            buffer_or_path.close()


def get_copyright_message(prefix="! "):
    return textwrap.indent(
        "-"*45 + f"""\nGenerated by oplus version {__version__}
Copyright (c) {dt.datetime.now().year}, Openergy development team
http://www.openergy.fr
https://github.com/openergy/oplus\n""" + "-"*45 + "\n\n",
        prefix,
        lambda line: True)
