import json
import datetime as dt
import textwrap

from .. import __version__


def table_name_to_ref(name):
    return name.replace(":", "_")


def multi_mode_write(buffer_writer, string_writer, buffer_or_path=None):
    # manage string mode
    if buffer_or_path is None:
        return string_writer()

    # manage buffer mode
    if isinstance(buffer_or_path, str):
        buffer = open(buffer_or_path, "w")
    else:
        buffer = buffer_or_path

    with buffer:
        buffer_writer(buffer)


def json_data_to_json(json_data, buffer_or_path=None, indent=2):
    return multi_mode_write(
        lambda buffer: json.dump(json_data, buffer, indent=indent),
        lambda: json.dumps(json_data, indent=indent),
        buffer_or_path=buffer_or_path
    )


def get_copyright_message(prefix="! "):
    return textwrap.indent(
        "-"*45 + f"""\nGenerated by oplus version {__version__}
Copyright (c) {dt.datetime.now().year}, Openergy development team
http://www.openergy.fr
https://github.com/openergy/oplus\n""" + "-"*45 + "\n\n",
        prefix,
        lambda line: True
    )
